SRCS = ft_printf.c ft_putnbr_base.c handle_numbers.c
CC = gcc

FLAGS = -c -Wall -Wextra -Werror
LIBFT = ./libft/libft.a

N_TEMP = temp.a

NAME = libftprintf.a
INCLUDES = -I.1/includes

OBJS = $(SRCS:.c=.o)

$(NAME): $(OBJS)
	$(MAKE) bonus -C ./libft
	cp libft/libft.a $(NAME)
	$(CC) $(FLAGS) $(INCLUDES) $(SRCS)
	ar -rcs $(NAME) $(OBJS)

all : $(NAME)

clean :
	$(MAKE) clean -C ./libft
	rm -rf $(SURPL_O)
	rm -rf $(OBJS)

fclean : clean
	$(MAKE) fclean -C ./libft
	rm -rf $(NAME)

re : fclean all
